var traducoes = {
    'pt': {
      'txt-01': 'Cardápio',
      'txt-02': 'História',
      'txt-03': 'Pedidos',
      'txt-04': 'Reservas',
      'txt-05': 'Bem Vindo',
      'txt-06': 'Escolha a lingua de sua preferencia',
      'txt-07': 'Visite nossa instagram:',
      'txt-08': '@borcelle',
      'txt-09': 'Fique Antenado',
      'txt-10': 'Grupo do Telegram',
      'txt-11': 'Entre no nosso grupo e saiba quando teremos especialidades.',
      'txt-12': 'Como tudo',
      'txt-13': 'começou',
      'txt-14': 'PORTUGUES. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita est placeat autem cupiditate possimus laudantium tempore perferendis commodi quibusdam sit ipsa vero consequatur vitae, illum repellendus sint nam. Officia, accusamus.',
      'txt-15': 'Saiba Mais',
      'txt-16': 'PORTUGUES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-17': 'PORTUGUES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-18': 'PORTUGUES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-19': 'PORTUGUES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-20': 'PORTUGUES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-21': 'Entradas',
      'txt-22': 'Prato Principal',
      'txt-23': 'Bebidas',
      'txt-24': 'Sobremesa',
      'txt-25': 'Nome do Prato',
      'txt-26': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-27': 'Nome do Prato',
      'txt-28': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-29': 'Nome do Prato',
      'txt-30': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-31': 'Nome do Prato',
      'txt-32': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-33': 'Nome do Prato',
      'txt-34': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-35': 'Nome do Prato',
      'txt-36': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-37': 'Nome do Prato',
      'txt-38': 'Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc. Descrição do prato vai aqui. Pode incluir ingredientes, sabores, etc.',
      'txt-39': 'Reservas & Delivery',
      'txt-40': 'Pedidos e horários',
      'txt-41': 'Peça agora mesmo pelo nossos telefones, Whatsapp ou ',
      'txt-42': 'através de nossos parceiros:',
      'txt-43': 'Almoço',
      'txt-44': 'TERÇA A SEXTA: 12:00h - 15:00h',
      'txt-45': 'SÁBADO: 12:00h - 16:00h',
      'txt-46': 'DOMINGO: 12:00h - 17:00h',
      'txt-47': 'Jantar',
      'txt-48': 'TERÇA A QUINTA: 19:00h - 23:00h',
      'txt-49': 'SEXTA E SÁBADO: 19:00h - 00:00h',
      'txt-50': 'DOMINGO: 19:00h - 22:30h',
      'txt-51': 'Localização e áreas de entrega:',
      'txt-52': 'Rua exemplo nº00 9999-9999',
      'txt-53': 'Direitos Reservados',
      'txt-54': '',
      'txt-55': '',
      'txt-56': '',
      'txt-57': '',
      'txt-58': '',
      'txt-59': '',
      'txt-60': ''
      // ...
    },
    'en': {
      'txt-01': 'Menu',
      'txt-02': 'History',
      'txt-03': 'Requests',
      'txt-04': 'Reservations',
      'txt-05': 'Welcome',
      'txt-06': 'Choose your preferred language',
      'txt-07': 'Visit our Instagram:',
      'txt-08': '@borcelle',
      'txt-09': 'Stay Tuned',
      'txt-10': 'Telegram Group',
      'txt-11': 'Join our group and find out when we will have specials.',
      'txt-12': 'How it all ',
      'txt-13': 'began',
      'txt-14': 'INGLES. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita est placeat autem cupiditate possimus laudantium tempore perferendis commodi quibusdam sit ipsa vero consequatur vitae, illum repellendus sint nam. Officia, accusamus.',
      'txt-15': 'Know more',
      'txt-16': 'INGLES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-17': 'INGLES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-18': 'INGLES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-19': 'INGLES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-20': 'INGLES. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-21': 'Appetizer',
      'txt-22': 'Main course',
      'txt-23': 'Drinks',
      'txt-24': 'Dessert',
      'txt-25': 'plate name',
      'txt-26': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-27': 'plate name',
      'txt-28': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-29': 'plate name',
      'txt-30': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-31': 'plate name',
      'txt-32': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-33': 'plate name',
      'txt-34': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-35': 'plate name',
      'txt-36': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-37': 'plate name',
      'txt-38': 'Description of the dish goes here. It can include ingredients, flavors, etc. Description of the dish goes here. It can include ingredients, flavors, etc.',
      'txt-39': 'Reservations & Delivery',
      'txt-40': 'Orders and schedules',
      'txt-41': 'Order now via our phones, Whatsapp or ',
      'txt-42': 'through our partners:',
      'txt-43': 'Lunch',
      'txt-44': 'TUESDAY TO FRIDAY: 12:00pm - 3:00pm',
      'txt-45': 'SATURDAY: 12:00pm - 4:00pm',
      'txt-46': 'SUNDAY: 12:00pm - 5:00pm',
      'txt-47': 'Dinner',
      'txt-48': 'TUESDAY TO THURSDAY: 7:00 pm - 11:00 pm',
      'txt-49': 'FRIDAY AND SATURDAY: 19:00 pm - 00:00 pm',
      'txt-50': 'SUNDAY: 07:00 pm - 10:30 pm',
      'txt-51': 'Location and delivery areas:',
      'txt-52': 'Street bla bla bla',
      'txt-53': 'Rights Reserved',
      'txt-54': '',
      'txt-55': '',
      'txt-56': '',
      'txt-57': '',
      'txt-58': '',
      'txt-59': '',
      'txt-60': ''
      // ...
    },
    'es': {
      'txt-01': 'Menú',
      'txt-02': 'Historia',
      'txt-03': 'Peticiones',
      'txt-04': 'Reservas',
      'txt-05': 'Bienvenido',
      'txt-06': 'Elige tu idioma preferido',
      'txt-07': 'Visita nuestro Instagram:',
      'txt-08': '@borcelle',
      'txt-09': 'Manténganse al tanto',
      'txt-10': 'Grupo de Telegram',
      'txt-11': 'Únase a nuestro grupo y descubra cuándo tendremos ofertas especiales.',
      'txt-12': 'Cómo todo ',
      'txt-13': 'empezo',
      'txt-14': 'ESPANHOL. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita est placeat autem cupiditate possimus laudantium tempore perferendis commodi quibusdam sit ipsa vero consequatur vitae, illum repellendus sint nam. Officia, accusamus.',
      'txt-15': 'Sepa mas',
      'txt-16': 'ESPANHOL. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-17': 'ESPANHOL. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-18': 'ESPANHOL. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-19': 'ESPANHOL. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-20': 'ESPANHOL. Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'txt-21': 'Aperitivo',
      'txt-22': 'Plato principal',
      'txt-23': 'Bebidas',
      'txt-24': 'Postre',
      'txt-25': 'nombre del plato',
      'txt-26': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-27': 'nombre del plato',
      'txt-28': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-29': 'nombre del plato',
      'txt-30': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-31': 'nombre del plato',
      'txt-32': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-33': 'nombre del plato',
      'txt-34': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-35': 'nombre del plato',
      'txt-36': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-37': 'nombre del plato',
      'txt-38': 'La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc. La descripción del plato va aquí. Puede incluir ingredientes, sabores, etc.',
      'txt-39': 'Reservas y Entrega',
      'txt-40': 'Pedidos y horarios',
      'txt-41': 'Haga su pedido ahora a través de nuestros teléfonos, Whatsapp o ',
      'txt-42': 'a través de nuestros socios:',
      'txt-43': 'Almuerzo',
      'txt-44': 'MARTES A VIERNES: 12:00h - 15:00h',
      'txt-45': 'SÁBADO: 12:00h - 16:00h',
      'txt-46': 'DOMINGO: 12:00h - 17:00h',
      'txt-47': 'Cena',
      'txt-48': 'MARTES A JUEVES: 19:00h - 23:00h',
      'txt-49': 'VIERNES Y SÁBADO: 19:00h - 00:00h',
      'txt-50': 'DOMINGO: 19:00h - 22:30h',
      'txt-51': 'Ubicación y zonas de entrega:',
      'txt-52': 'Calle bla bla bla',
      'txt-53': 'Derechos reservados',
      'txt-54': '',
      'txt-55': '',
      'txt-56': '',
      'txt-57': '',
      'txt-58': '',
      'txt-59': '',
      'txt-60': ''
      // ...
    }
  };
  
  // Função para mudar o idioma
  function mudarIdioma(lang) {
    document.querySelectorAll("[data-txt]").forEach(function(el) {
      var chave = el.getAttribute("data-txt");
      el.textContent = traducoes[lang][chave];
    });
  }
  
  // Definir inglês como idioma padrão ao carregar a página
  document.addEventListener('DOMContentLoaded', function() {
    mudarIdioma('pt');
  });